# Generated by Django 6.0.2 on 2026-02-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="default", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
