# Generated by Django 6.0.2 on 2026-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="favorite_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
